### ISSUE TITLE
gene_finder.py: error: unrecognized arguments: –1 ../../PATH/read_1.fastq

### ISSUE THREAD

**Issue by RicardoGCCR** [phe-bioinformatics/gene_finder#3]
Hi, 
Thank you for this tool. 
I really want it to use it but I havent been able to... Once I run the script I get the following error: 

"gene_finder.py: error: unrecognized arguments: –1 ../../PATH/read_1.fastq"
or
"gene_finder.py: error: unrecognized arguments: –fastq_1 ../../PATH/read_1.fastq"

Any idea what is going wrong?
Thanks, 
Ricardo

**Comment by ulfschaefer** [comment]
I am not sure. At first glance they look like odd hyphen/minus characters. -1 vs your –1. Is that a normal - (ascii 45)?

**Comment by RicardoGCCR** [comment]
Yes, that was it! It is fixed now! Thank you!!
